# Generated by Django 5.2.7 on 2025-11-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceoffer',
            name='currency',
            field=models.CharField(default='MAD', max_length=8),
        ),
        migrations.AddField(
            model_name='priceoffer',
            name='raw_price_text',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='raw_price_map',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='raw_url_map',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='source_category',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='priceoffer',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
