# Generated by Django 5.2.7 on 2025-12-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_approval_status_product_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
