# Generated by Django 5.2.7 on 2025-12-24 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_subcategory_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='priceoffer',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='priceoffer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priceoffer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='priceoffer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='priceoffer',
            name='merchant_name',
            field=models.CharField(blank=True, help_text='Merchant name if creating new merchant', max_length=150),
        ),
        migrations.AddField(
            model_name='priceoffer',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
