# Generated by Django 5.2.7 on 2025-12-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_image_url_to_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='logo_file',
            field=models.ImageField(blank=True, help_text='Uploaded logo file', null=True, upload_to='merchants/'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='logo',
            field=models.URLField(blank=True, help_text='External logo URL'),
        ),
    ]
