# Generated by Django 5.2.7 on 2025-11-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visiteur'), ('client', 'Client'), ('admin', 'Admin')], default='visitor', max_length=10),
        ),
    ]
