# Generated by Django 5.2.7 on 2025-11-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='adresse'),
        ),
        migrations.AddField(
            model_name='user',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='numéro de téléphone'),
        ),
    ]
