# Generated by Django 5.2.7 on 2025-11-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_address_user_enterprise_name_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visiteur'), ('user', 'Utilisateur'), ('client', 'Client'), ('admin', 'Admin')], default='visitor', max_length=10),
        ),
    ]
