# Generated by Django 5.2.7 on 2025-10-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('general', 'Général'), ('products', 'Produits'), ('prices', 'Prix'), ('merchants', 'Marchands')], default='general', max_length=32)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['section', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
