# Generated by Django 5.2.7 on 2026-01-14 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sitesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Extrait')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image mise en avant')),
                ('featured_image_url', models.URLField(blank=True, help_text="URL externe de l'image mise en avant")),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta titre (SEO)')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta description (SEO)')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Mots-clés (SEO)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
