# Generated by Django 5.2.7 on 2026-01-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('homepage', "Page d'accueil"), ('blog_list', 'Liste des blogs'), ('blog_detail', 'Détail du blog'), ('product_detail', 'Détail du produit'), ('category_list', 'Liste des catégories'), ('category_detail', 'Détail de la catégorie'), ('deals', 'Bons plans'), ('search', 'Recherche'), ('magic_tool', 'Outil magique'), ('dashboard', 'Tableau de bord'), ('faq', 'FAQ'), ('all', 'Toutes les pages')], max_length=50, verbose_name='Type de page')),
                ('slot', models.CharField(choices=[('top', 'Haut'), ('middle', 'Milieu'), ('bottom', 'Bas'), ('sidebar', 'Barre latérale'), ('header', 'En-tête'), ('footer', 'Pied de page')], max_length=50, verbose_name='Emplacement')),
                ('ad_type', models.CharField(choices=[('adsense', 'AdSense'), ('banner_image', 'Image bannière'), ('custom_code', 'Code personnalisé')], max_length=50, verbose_name="Type d'annonce")),
                ('adsense_id', models.CharField(blank=True, max_length=200, verbose_name='ID AdSense')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='adsense/banners/', verbose_name='Image bannière')),
                ('banner_image_url', models.URLField(blank=True, help_text="URL externe de l'image bannière")),
                ('banner_link', models.URLField(blank=True, verbose_name='Lien de la bannière')),
                ('custom_code', models.TextField(blank=True, verbose_name='Code personnalisé (HTML/JavaScript)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='adsense/backgrounds/', verbose_name='Image de fond')),
                ('background_image_url', models.URLField(blank=True, help_text="URL externe de l'image de fond")),
                ('enabled', models.BooleanField(default=True, verbose_name='Activé')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Configuration d'annonce par page",
                'verbose_name_plural': "Configurations d'annonces par page",
                'ordering': ['page_type', 'slot', 'order'],
                'unique_together': {('page_type', 'slot', 'order')},
            },
        ),
    ]
